In [24]:
import keras
import time
import pandas as pd

In [3]:
(train_images, train_labels), (test_images, test_labels) = keras.datasets.fashion_mnist.load_data()

In [4]:
train_images, test_images = train_images / 255.0, test_images / 255.0

Буду виконувати через згортку і dense, почну з dense для тесту оптималізаторів

In [39]:
optimizers = {
    'SGD': 'sgd',
    'RMSprop': 'rmsprop',
    'Adam': 'adam'
}
results_data = []

In [40]:
def get_dense():
    inputs = keras.Input(shape=(28, 28))
    x = keras.layers.Flatten()(inputs)
    x = keras.layers.Dense(128, activation='relu')(x)
    outputs = keras.layers.Dense(10, activation='softmax')(x)
    model = keras.Model(inputs=inputs, outputs=outputs)
    return model

In [41]:
for name, optimizer in optimizers.items():
    keras.utils.set_random_seed(42)
    
    model = get_dense()
    model.compile(optimizer=optimizer,
			loss='sparse_categorical_crossentropy',
			metrics=['accuracy'])
    
    print (f'Training with {name} optimizer')
    
    start_time = time.time()
    
    history = model.fit(
		train_images,      
        train_labels, 
        epochs=5,          
        batch_size=64
    )
    
    end_time = time.time()
    
    train_time = end_time - start_time

    test_loss, test_acc = model.evaluate(test_images, test_labels)
    
    results_data.append({
            "Model Type": 'Dense',
            "Optimizer": name,
            "Train Accuracy": f"{history.history['accuracy'][-1]:.4f}",
            "Train Loss": f"{history.history['loss'][-1]:.4f}",
            "Test Accuracy": f"{test_acc:.4f}",
            "Test Loss": f"{test_loss:.4f}",
            "Time": f"{train_time:.2f}"
        })

Training with SGD optimizer
Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.7250 - loss: 0.8786
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8104 - loss: 0.5766
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8269 - loss: 0.5168
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.8348 - loss: 0.4863
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8409 - loss: 0.4663
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8220 - loss: 0.5072
Training with RMSprop optimizer
Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8130 - loss: 0.5301
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8594 - loss: 0.3869
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8753 - loss: 0.3447
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8840 - loss: 0.3196
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8908 - loss: 0.3021
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8510 - loss: 0.4351
Training with Adam optimizer
Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.8219 - loss: 0.5115
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8641 - loss: 0.3811
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8779 - loss: 0.3408
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8854 - loss: 0.3169
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8919 - loss: 0.2984
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8712 - loss: 0.3643

Зробимо результати

In [42]:
def get_conv():
    inputs = keras.Input(shape=(28, 28, 1))
    x = keras.layers.Conv2D(32, (3, 3), activation='relu')(inputs)
    x = keras.layers.MaxPooling2D((2, 2))(x)
    x = keras.layers.Flatten()(x)
    outputs = keras.layers.Dense(10, activation='softmax')(x)
    return keras.Model(inputs=inputs, outputs=outputs)

In [43]:
for name, optimizer in optimizers.items():
    keras.utils.set_random_seed(42)
    
    model = get_conv()
    model.compile(optimizer=optimizer,
			loss='sparse_categorical_crossentropy',
			metrics=['accuracy'])
    
    print (f'Training with {name} optimizer')
    
    start_time = time.time()
    
    history = model.fit(
		train_images,      
        train_labels, 
        epochs=5,          
        batch_size=64
    )
    
    end_time = time.time()
    train_time = end_time - start_time

    test_loss, test_acc = model.evaluate(test_images, test_labels)
    
    results_data.append({
            "Model Type": 'Conv2D',
            "Optimizer": name,
            "Train Accuracy": f"{history.history['accuracy'][-1]:.4f}",
            "Train Loss": f"{history.history['loss'][-1]:.4f}",
            "Test Accuracy": f"{test_acc:.4f}",
            "Test Loss": f"{test_loss:.4f}",
            "Time": f"{train_time:.2f}"
        })

Training with SGD optimizer
Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.7156 - loss: 0.8567
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8031 - loss: 0.5530
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.8197 - loss: 0.5099
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8303 - loss: 0.4833
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8383 - loss: 0.4626
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7843 - loss: 0.5834
Training with RMSprop optimizer
Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8291 - loss: 0.4870
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8840 - loss: 0.3358
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8969 - loss: 0.2981
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.9038 - loss: 0.2767
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9098 - loss: 0.2614
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8919 - loss: 0.3066
Training with Adam optimizer
Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8347 - loss: 0.4751
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8852 - loss: 0.3303
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8967 - loss: 0.2958
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.9036 - loss: 0.2743
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.9089 - loss: 0.2580
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8917 - loss: 0.2961

In [44]:
df_results = pd.DataFrame(results_data)
df_results

,Model Type,Optimizer,Train Accuracy,Train Loss,Test Accuracy,Test Loss,Time
0,Dense,SGD,0.8409,0.4663,0.8220,0.5072,23.79
1,Dense,RMSprop,0.8908,0.3021,0.8510,0.4351,20.24
2,Dense,Adam,0.8919,0.2984,0.8712,0.3643,19.94
3,Conv2D,SGD,0.8383,0.4626,0.7843,0.5834,22.95
4,Conv2D,RMSprop,0.9098,0.2614,0.8919,0.3066,23.67
5,Conv2D,Adam,0.9089,0.2580,0.8917,0.2961,23.45

Найточніша на цьому датасеті виявилась згорткова модель з оптімізатором RMSprop, так ще ї найшвидше серед згорткових моделей.

Трішки гірше впоралась згорткова з Адамом та вона виявилась трошки довша.

Найгірше та найдовше з усіх впоралась згорткова з SGD оптимізацією.

Серед Dense найкраще та з усіх найшвидше впоралась оптимізація Adam. Загалом Dense працювала швидке ніж згорткова

Тепер я хочу погратися з налаштуванням оптимізаторів, візьму Dense RMSprop та Conv2D Adam

In [45]:
learning_rates = [0.3, 0.1, 0.03, 0.01, 0.003, 0.001]
results = []

In [46]:
for i in learning_rates:
    
    model = get_dense()
    optimizer_dense = keras.optimizers.RMSprop(learning_rate=i)
    model.compile(optimizer=optimizer_dense,
			loss='sparse_categorical_crossentropy',
			metrics=['accuracy'])
    start_time = time.time()
    history_dense = model.fit(
		train_images,      
        train_labels, 
        epochs=5,          
        batch_size=64
    )
    end_time = time.time()
    train_time = end_time - start_time
    test_loss, test_acc = model.evaluate(test_images, test_labels)
    results.append({
        "Model Type": 'Dense',
        "Optimizer": f"RMSprop (lr={i})",
        "Train Accuracy": f"{history_dense.history['accuracy'][-1]:.4f}",
        "Train Loss": f"{history_dense.history['loss'][-1]:.4f}",
        "Test Accuracy": f"{test_acc:.4f}",
        "Test Loss": f"{test_loss:.4f}",
        "Time": f"{train_time:.2f}"
    })
    
    model = get_conv()
    optimizer_conv = keras.optimizers.Adam(learning_rate=i)
    model.compile(optimizer=optimizer_conv,
			loss='sparse_categorical_crossentropy',
			metrics=['accuracy'])
    start_time = time.time()
    history_conv = model.fit(
		train_images,      
        train_labels, 
        epochs=5,          
        batch_size=64
    )
    end_time = time.time()
    train_time = end_time - start_time
    test_loss, test_acc = model.evaluate(test_images, test_labels)
    
    results.append({
        "Model Type": 'Conv2D',
        "Optimizer": f"Adam (lr={i})",
        "Train Accuracy": f"{history_conv.history['accuracy'][-1]:.4f}",
        "Train Loss": f"{history_conv.history['loss'][-1]:.4f}",
        "Test Accuracy": f"{test_acc:.4f}",
        "Test Loss": f"{test_loss:.4f}",
        "Time": f"{train_time:.2f}"
    })

Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - accuracy: 0.1454 - loss: 17.5390
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.1270 - loss: 2.2904
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.1312 - loss: 2.2975
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.1372 - loss: 2.2844
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.1411 - loss: 2.2620
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.1501 - loss: 2.2657
Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.1010 - loss: 3.3149
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.0980 - loss: 2.3267
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.0985 - loss: 2.3269
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.0987 - loss: 2.3270
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.0987 - loss: 2.3270
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.1000 - loss: 2.3130
Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.4083 - loss: 3.2002
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.3822 - loss: 1.7090
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.3794 - loss: 1.6764
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.3875 - loss: 1.6369
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.3901 - loss: 1.6604
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.4091 - loss: 1.6358
Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.7925 - loss: 0.6612
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.8030 - loss: 0.5763
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8011 - loss: 0.5774
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7971 - loss: 0.5879
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8020 - loss: 0.5647
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.7886 - loss: 0.5933
Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.7139 - loss: 0.9674
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7809 - loss: 0.6506
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7959 - loss: 0.6234
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8030 - loss: 0.6073
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8070 - loss: 0.6026
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7667 - loss: 0.9661
Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8446 - loss: 0.4432
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.8695 - loss: 0.3685
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8627 - loss: 0.3785
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8666 - loss: 0.3671
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8704 - loss: 0.3560
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8552 - loss: 0.4260
Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.7891 - loss: 0.6238
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8395 - loss: 0.4592
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8540 - loss: 0.4258
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.8595 - loss: 0.4095
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8640 - loss: 0.4033
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8166 - loss: 0.6030
Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8638 - loss: 0.3859
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8954 - loss: 0.2964
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.9051 - loss: 0.2628
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9108 - loss: 0.2440
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.9184 - loss: 0.2251
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8830 - loss: 0.3664
Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8080 - loss: 0.5321
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8582 - loss: 0.3891
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8715 - loss: 0.3562
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8786 - loss: 0.3378
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8859 - loss: 0.3206
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8408 - loss: 0.5030
Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.8569 - loss: 0.4023
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8980 - loss: 0.2875
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.9088 - loss: 0.2551
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9172 - loss: 0.2316
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9235 - loss: 0.2128
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9013 - loss: 0.2837
Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8133 - loss: 0.5313
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8594 - loss: 0.3906
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8737 - loss: 0.3476
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8831 - loss: 0.3221
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8905 - loss: 0.3037
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8488 - loss: 0.4412
Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.8324 - loss: 0.4831
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.8820 - loss: 0.3386
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8953 - loss: 0.3004
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9030 - loss: 0.2767
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.9085 - loss: 0.2592
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8950 - loss: 0.2928

In [56]:
df_results = pd.DataFrame(results)
df_results.sort_values(by=['Test Accuracy'], inplace=True)
df_results

,Model Type,Optimizer,Train Accuracy,Train Loss,Test Accuracy,Test Loss,Time
1,Conv2D,Adam (lr=0.3),0.0987,2.3270,0.1000,2.3130,25.48
0,Dense,RMSprop (lr=0.3),0.1411,2.2620,0.1501,2.2657,22.46
2,Dense,RMSprop (lr=0.1),0.3901,1.6604,0.4091,1.6358,21.45
4,Dense,RMSprop (lr=0.03),0.8070,0.6026,0.7667,0.9661,20.65
3,Conv2D,Adam (lr=0.1),0.8020,0.5647,0.7886,0.5933,25.34
6,Dense,RMSprop (lr=0.01),0.8640,0.4033,0.8166,0.6030,22.64
8,Dense,RMSprop (lr=0.003),0.8859,0.3206,0.8408,0.5030,18.39
10,Dense,RMSprop (lr=0.001),0.8905,0.3037,0.8488,0.4412,19.82
5,Conv2D,Adam (lr=0.03),0.8704,0.3560,0.8552,0.4260,25.02
7,Conv2D,Adam (lr=0.01),0.9184,0.2251,0.8830,0.3664,26.08
11,Conv2D,Adam (lr=0.001),0.9085,0.2592,0.8950,0.2928,26.28
9,Conv2D,Adam (lr=0.003),0.9235,0.2128,0.9013,0.2837,26.44

Бачимо, що набагато краще вийшло у згортки при 0.003 ступені навчання, але вона ж і найдовше навчалась.

Видно що має сенс ставити lr < 0.1, та на цьому датасеті в тисячних lr веде себе найкраще